In [ ]:
import numpy as np

print('NumPy version:', np.__version__)

NumPy version: 2.0.2


In [ ]:
# From a Python list

a = np.array([1, 2, 3, 4, 5])

print('Array:', a)
print('Shape:', a.shape)    # (5,) — 1-D, 5 elements
print('Dtype:', a.dtype)    # int64 by default
print('Ndim:', a.ndim)      # 1


Array: [1 2 3 4 5]
Shape: (5,)
Dtype: int64
Ndim: 1


In [ ]:
# 2-D array (matrix)

mat = np.array([[1, 2, 3],
                [4, 5, 6]])

print('Shape:', mat.shape)   # (2, 3) — 2 rows, 3 cols
print(mat)

Shape: (2, 3)
[[1 2 3]
 [4 5 6]]


In [4]:
# YOUR TURN
# Create 3x3 array random floats between 0 and 1.
# Print its shape, dtype, and the value at row 1, col 2.

arr = np.random.rand(3, 3)

print(arr)

print("Shape:", arr.shape)
print("Dtype:", arr.dtype)

print("Value at row 1, col 2:", arr[1, 2])

[[0.86337244 0.4007026  0.71421611]
 [0.61151733 0.8894015  0.45905759]
 [0.55610773 0.26636175 0.95569839]]
Shape: (3, 3)
Dtype: float64
Value at row 1, col 2: 0.45905759270389346
